/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import com.sun.jndi.cosnaming.IiopUrl.Address;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Yuyutsu Poudel
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public Index() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(425, 550));
        getContentPane().setLayout(null);

        jLabel2.setText("Please enter username and password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 110, 261, 15);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(160, 180, 220, 30);

        jLabel3.setText("Username:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 190, 74, 15);

        jLabel4.setText("Password:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 250, 70, 15);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("BHARATPUR HOTEL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 20, 240, 29);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(160, 240, 220, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Admin" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(160, 310, 81, 24);

        jLabel5.setText("User Type: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 310, 77, 15);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 450, 79, 25);

        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 450, 72, 25);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/icons8-user-24.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 180, 30, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/icons8-password-26.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 240, 26, 30);

        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 140, 330, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/slider-back-hotel.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 390, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            String user = jTextField1.getText();
            String pass = jPasswordField1.getText();
            String idtype = jComboBox1.getSelectedItem().toString();
            String sql = "Select * from login where user = ? and pass = ? and type = ? ";
            Class.forName("com.mysql.jdbc.Driver");
            Connection conc= DriverManager.getConnection("jdbc:mysql://localhost:3306/hms", "root", "");
            PreparedStatement ps = conc.prepareStatement(sql);
            ps.setString(1,user);
            ps.setString(2,pass);
            ps.setString(3,idtype);
            ResultSet rs = ps.executeQuery(); 
            String retUsername="0";
            String retPassword ="0";
            while (rs.next()){
                retUsername = rs.getString("user");
                retPassword = rs.getString("pass");
                idtype = rs.getString("type");
            }
            if(user.equals(retUsername) && pass.equals(retPassword) && idtype.equals("admin")){
                //JOptionPane.showMessageDialog(rootPane, "admin");
                AdminMenu info = new AdminMenu();
                info.setVisible(true);
                this.setVisible(false);
            }
            else if(user.equals(retUsername) && pass.equals(retPassword) && idtype.equals("general")){
                //JOptionPane.showMessageDialog(rootPane, "general");
                GeneralMenu info2 = new GeneralMenu();
                info2.setVisible(true);
                this.setVisible(false);
            }
            else{
                //JOptionPane.showMessageDialog(rootPane, "Username or password error.");
                jTextField1.setText("");
                jPasswordField1.setText("");
                jLabel9.setText("Username or password error.");
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Server error. Are you sure database is connected?");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            
        }
        
    }//GEN-LAST:event_jTextField1KeyPressed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
